eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: products
          uri: http://localhost:8081
          predicates:
            - Path=/product/**
        - id: payments
          uri: http://localhost:8082
          predicates:
            - Path=/payment/**
        - id: orders
          uri: http://localhost:8083
          predicates:
            - Path=/order/**

management:
  tracing:
    sampling:
      probability: 1.0