server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product-service-db
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    enabled-by-default: false
  web:
    exposure:
      include: 'health,metrics,info'
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    info:
      enabled: true